[build]
  publish = "dist"  # Specify your build folder, typically "dist" or "build"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"  # Ensure .js files are served with the correct MIME type

[[headers]]
  for = "/index.html"  # For HTML file
  [headers.values]
    Content-Type = "text/html"